build: generator.cc tabuSearch.cc beamSearch.cc vnd.cc
	g++ generator.cc -o clause_generator
	g++ tabuSearch.cc -o tabuSearch
	g++ beamSearch.cc -o beamSearch 
	g++ vnd.cc -o vnd

view:
	cat readable_CNF.txt
	cat CNF.txt
